version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${dbPassword:-mysecretpassword}
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    env_file:
      - .env
    build:
      context: ./
    image: 5200710/yinxiang:0.0.1
volumes:
  postgres-data:
