yinxiang:
  devToken: ${devToken}
  noteStoreUrl: ${noteStoreUrl}
  filterNoteBooks:
    - "the name of notebook that you want to filtered"
    - "the name of notebook that you want to filtered"
  filterNotes:
    - "the name of note that you want to filtered"
    - "the name of note that you want to filtered"
  sync:
    schedule: 0 0 10,14,18,22 * * ?
spring:
  thymeleaf:
    cache: false

  devtools:
    restart:
      additional-paths:
        - "yinxiang/src/main/java"
        - "**/resources/templates"
  datasource:
    url: jdbc:postgresql://localhost:5432/yinxiang?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: ${dbPassword:mysecretpassword}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        create: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        temp:
          use_jdbc_metadata_defaults: false